name: Nightly build
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LITOROMTOKEN }}
    - name: Read game profile configs
      run: |
        source game_profile.conf
        echo "GAME_VER=$version" >> $GITHUB_ENV
        echo "DEV_BUILD=$devBuild" >> $GITHUB_ENV
    # Do no increment game version if it is not currently in a development build state.
    # Source: https://stackoverflow.com/a/75809743
    - name: Abort
      if: ${{ ! env.DEV_BUILD }}
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Increment game version
      run: |
        dev_num=$( [[ $GAME_VER = *"dev"* ]] && ( echo $GAME_VER | grep -Po "[0-9.]+-dev\K\d+" ) || ( echo 0 ) )
        ((dev_num++))
        base_ver=$( echo $GAME_VER | grep -o "^[^-]*" )
        echo "GAME_VER=$base_ver-dev$dev_num" >> $GITHUB_ENV
    - name: Update game version
      run: sed -E -i "/^version=.+$/ s/[0-9]+.+$/$GAME_VER/" game_profile.conf
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Increment Version"
        token: ${{ secrets.LITOROMTOKEN }}
        repository: ${{ secrets.GITHUB_REPOSITORY }}
        branch: ${{ github.ref }}

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    - name: Execute Gradle build
      run: ./gradlew build
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ vars.VERSION }}-dev${{ vars.VERSION_s }}"
        prerelease: true
        title: "Version ${{ vars.VERSION }}, Pre-release ${{ vars.VERSION_s }} (Nightly)"
        generate_release_notes: true
        files: |
          LICENSE
          ChangeLog.md
          build/libs/**.jar

