name: Auto Label on Comment

on:
  issue_comment:
    types: [created]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add label # Credit: Copilot
        run: |
          AUTHOR="${{ github.event.comment.user.login }}"
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "${COMMENT_BODY,,}" =~ ^superseded\ by.* ]] && [[ "$AUTHOR" == "dependabot" || "$(gh api user/$AUTHOR | jq -r '.site_admin')" == "true" ]]; then
            gh auth login --with-token $GITHUB_TOKEN
            gh issue edit ${{ github.event.issue.id }} --add-label "status: Superseded"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
